// This file is generated by PBX. You should never modify it.
namespace PBX
{
	public class MsgID
	{

		// chat.proto
		public const ushort sendMsg = 1001;
		public const ushort recvMsg = 1002;

		// login.proto
		public const ushort gcLoginRoleInfo = 2001;
		public const ushort cgLogin = 2002;
		public const ushort gcLoginRet = 2003;
		public const ushort cgLogout = 2004;
		public const ushort gcLogoutRet = 2005;
		public const ushort cgEnterGame = 2006;
		public const ushort gcEnterGameRet = 2007;

		// scene.proto
		public const ushort gcPlayerInfo = 3001;
		public const ushort gcEnterScene = 3002;
		public const ushort cgEnterSceneDone = 3003;
		public const ushort cgExitScene = 3004;
		public const ushort gcExitSceneRet = 3005;
		public const ushort gcOtherEnterScene = 3006;
		public const ushort gcNearbyPlayerInfo = 3007;
		public const ushort cgMoveTo = 3008;
		public const ushort gcMoveTo = 3009;

	}
}
